name: Deploy to Ubuntu Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build VuePress
        run: npm run docs:build

      - name: Deploy to Ubuntu Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}  # 服务器IP
          username: ${{ secrets.SSH_USERNAME }}  # 如 root 或 ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # ~/.ssh/id_rsa 内容
          source: "docs/.vuepress/dist/"
          target: "/home/lee/MyDoc/.vuepress/dist"  # 服务器目标目录
